# Dimensions of simulation shapes
MAP_WIDTH = 512
MAP_HEIGHT = 512
SPAWN_AREA_WIDTH = 128
IMAGE_WIDTH = MAP_WIDTH + SPAWN_AREA_WIDTH * 2
IMAGE_HEIGHT = MAP_HEIGHT + SPAWN_AREA_WIDTH * 2
PEDESTRIAN_WIDTH = 20
PEDESTRIAN_HEIGHT = 20
BICYCLE_WIDTH = 15
BICYCLE_HEIGHT = 60
CAR_WIDTH = 60
CAR_HEIGHT = 110

# Maximum Velocities
PEDESTRIAN_MAX_SPEED = 1.5
BICYCLE_MAX_SPEED = 4
CAR_MAX_SPEED = 8

# Maximum Steering Forces
PEDESTRIAN_MAX_STEERING_FORCE = 0.2
BICYCLE_MAX_STEERING_FORCE = 0.1
CAR_MAX_STEERING_FORCE = 0.01

# Maximum Accelerations
PEDESTRIAN_MAX_ACCELERATION = 1
BICYCLE_MAX_ACCELERATION = 0.5
CAR_MAX_ACCELERATION = 0.4

# TARGET SETTING
TARGET_DELTA = 10

# Randomness factors
PEDESTRIAN_MOVEMENT_RANDOMNESS = 0.1
BICYCLE_MOVEMENT_RANDOMNESS = 0
CAR_MOVEMENT_RANDOMNESS = 0

# Danger-level view
DANGER_LEVEL_VIEW_DISTANCE = 100

# Inter-agent operation
MINIMUM_AGENT_DISTANCE = 20
AGENT_VISIBILITY_RANGE = 50

# Tick Parameters
PERCEPTION_DELAY = 3

# Simulation Parameters
DEFAULT_TIME_LIMIT = 300
