# Dimensions of simulation shapes
MAP_WIDTH = 512
MAP_HEIGHT = 512
PEDESTRIAN_WIDTH = 20
PEDESTRIAN_HEIGHT = 10
BICYCLE_WIDTH = 10
BICYCLE_HEIGHT = 50
CAR_WIDTH = 60
CAR_HEIGHT = 120

# Maximum Velocities
PEDESTRIAN_MAX_SPEED = 1.8
BICYCLE_MAX_SPEED = 5
CAR_MAX_SPEED = 10

# Maximum Steering Forces
PEDESTRIAN_MAX_STEERING_FORCE = 0.3
BICYCLE_MAX_STEERING_FORCE = 0.1
CAR_MAX_STEERING_FORCE = 0.01

# TARGET SETTING
TARGET_DELTA = 10

# Randomness factors
PEDESTRIAN_MOVEMENT_RANDOMNESS = 0.3
BICYCLE_MOVEMENT_RANDOMNESS = 0.2
CAR_MOVEMENT_RANDOMNESS = 0.05

# Inter-agent operation
MINIMUM_AGENT_DISTANCE = 20
AGENT_VISIBILITY_RANGE = 50
